name: 🌟 Feature Proposal
description: Suggest a new capability for Edge Craft or its tooling.
title: "[FEATURE] "
labels:
  - enhancement
  - needs-triage
body:
  - type: markdown
    attributes:
      value: |
        Thanks for improving Edge Craft. Feature requests should map to a PRP or propose a new one.

  - type: checkboxes
    id: alignment
    attributes:
      label: Alignment Checklist
      options:
        - label: I reviewed the existing PRPs and confirmed this is not already planned.
          required: true
        - label: I documented the business value and success metrics below.
          required: true
        - label: I am willing to help refine or implement this feature.
          required: true

  - type: textarea
    id: summary
    attributes:
      label: Feature summary
      description: Concise description of the capability you need.
      placeholder: Add support for SC2 tileset blending to improve terrain transitions.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Problem statement
      description: What problem does this feature solve? Reference user stories or PRPs.
      placeholder: Current terrain rendering produces harsh edges on SC2 maps lacking blend textures...
    validations:
      required: true

  - type: textarea
    id: success
    attributes:
      label: Success criteria
      description: How will we know this feature is complete? List measurable outcomes or validation steps.
      placeholder: |
        - Render SC2 tilesets with smooth blend masks
        - Maintain 60 FPS on 1080p builds
        - Automated regression scene for the Ashenvale sample map
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Proposed scope
      description: Outline components, formats, or pipelines affected.
      placeholder: |
        - Extend terrain shader to accept blend masks
        - Update asset validator to check for missing blend textures
        - Add unit tests for terrain material factory

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies & blockers
      description: List prerequisite work, assets, or external approvals.
      placeholder: Requires Babylon.js 6.x upgrade to access new node material API.

  - type: textarea
    id: risks
    attributes:
      label: Risks & tradeoffs
      description: Note performance, legal, or architecture concerns.

  - type: textarea
    id: references
    attributes:
      label: References
      description: Link demos, research papers, forum threads, or related issues.
