# Based on: https://github.com/BarthPaleologue/BabylonPlaywrightExample
FROM mcr.microsoft.com/playwright:v1.48.0-jammy

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy source code
COPY . .

# Run Playwright tests
CMD ["npx", "playwright", "test"]
