name: Update E2E Snapshots

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to update snapshots on'
        required: true
        default: 'dcversus/abu-dhabi-rebased'

jobs:
  update-snapshots:
    name: Update E2E Snapshots
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container:
      image: mcr.microsoft.com/playwright:v1.56.0-noble

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Update E2E snapshots
        run: npm run test:e2e:update-snapshots
        env:
          CI: true
          HOME: /root

      - name: Upload updated snapshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: updated-e2e-snapshots
          path: tests/e2e-screenshots/
          retention-days: 7

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push updated snapshots
        run: |
          git add tests/e2e-screenshots/
          if git diff --staged --quiet; then
            echo "No snapshot changes to commit"
          else
            git commit -m "test: Update E2E snapshots for Linux (CI)"
            git push origin ${{ github.event.inputs.branch }}
          fi

      - name: Comment on PR
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            const branch = '${{ github.event.inputs.branch }}';
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `${context.repo.owner}:${branch}`,
              state: 'open'
            });

            if (prs.length > 0) {
              const pr = prs[0];
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: '🎭 E2E snapshots have been updated for Linux CI environment. The E2E tests should pass now.'
              });
            }
